jobs:
  include:
    -
      name: Ubuntu 18.04
      dist: bionic
      language: python
      python:
        - "3.6"
      cache:
        directories:
          - "~/.platformio"
      addons:
        apt:
          packages: [ "libsdl2-dev:i386", gcc-multilib, g++-multilib ]
      install:
        - pip install -U platformio
        - platformio update
      script:
        # Test builds status
        - platformio run -e emulator
        - platformio run -e hardware_usb
        # Run tests
        - platformio test -e emulator
    -
      if: branch = ignore_all_until_travis_fixed
      name: macOS 10.14
      os: osx
      osx_image: xcode11.3
      language: shell
      cache:
        directories:
          - "~/.platformio"
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install sdl2
      install:
        - pip install -U platformio
        - platformio update
      script:
        # Test builds status
        #- platformio run -e emulator
        - platformio run -e hardware_usb
    -
      name: Windows
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell
      before_install:
        - choco install python --version 3.6.8
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
      install:
        - pip install -U platformio
        - platformio update
      script:
        # Test builds status
        - platformio run -e hardware_usb
