name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 3'

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
          platformio update

      - name: Build bare metal
        run: platformio run -e hardware_usb

      - name: Build desktop
        run: platformio run -e emulator

  macOS:
    runs-on: macos-latest
    steps:
      - name: Install macOS dependencies
        run: |
          HOMEBREW_NO_AUTO_UPDATE=1 brew install sdl2 binutils

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
          platformio update

      - name: Build bare metal
        run: platformio run -e hardware_usb

      # PIO uses old gcc on OSX for 'native', and ETL fails to build
      #- name: Build desktop
      #  run: platformio run -e emulator

  Windows:
    runs-on: windows-latest
    steps:
      - name: Activate msys2 & mingw64
        run: |
          echo "C:\msys64\usr\bin" >> $env:GITHUB_PATH
          echo "C:\msys64\mingw64\bin" >> $env:GITHUB_PATH

      - name: Install deps
        run: |
          pacman --noconfirm -S --needed mingw-w64-x86_64-SDL2
          gcc --version

      - uses: actions/checkout@v2
      #- uses: actions/setup-python@v1

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
          platformio update

      - name: Build bare metal
        run: platformio run -e hardware_usb

      - name: Build desktop
        run: platformio run -e emulator
